default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 20
development:
  <<: *default
  database: rails-autocomple_development
test:
  <<: *default
  database: rails-autocomple_test
